image: docker:19

stages:
  - build
  - deploy

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY_P" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - chmod 700 ~/.ssh
    
build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    
deploy_product:
  stage: deploy
  script:
    - ssh -p 2522 -A $PRO_SSH_ACC@$PRO_SSH_HOST 'docker rm -f skillab && docker rmi registry.gitlab.com/chienkakashi/skillab-website:latest && docker run -dit --name skillab -p 103.145.62.80:8005:80 registry.gitlab.com/chienkakashi/skillab-website'